spec:
  template:
    spec:
      containers:
      - name: wordpress
        readinessProbe:
          httpGet:
            path: /wp-admin/install.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10